### ISSUE TITLE
(Python 2.7, Django 1.9) Error: DjangoUnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128). You passed in <Address: [Bad Unicode data]> (<class 'ankets.models.Address'>)

### ISSUE THREAD

**Issue by RockBomber** [alepane21/django-nullablecharfield#5]
Hello!
Thanks for you field :)
But I've got error when saving field with non-ascii value :

```
/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/forms/fields.py:142: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value in self.empty_values and self.required:

/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/forms/fields.py:146: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value in self.empty_values:

/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/db/models/base.py:1153: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if f.blank and raw_value in f.empty_values:

/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:546: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value in self.empty_values:

/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/forms/fields.py:206: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return initial_value != data_value

Internal Server Error: /admin/ankets/address/2/change/
Traceback (most recent call last):
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1438, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1385, in changeform_view
    self.log_change(request, new_object, change_message)
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 730, in log_change
    object_repr=force_text(object),
  File "/home/asdef/.virtualenvs/autotesting/local/lib/python2.7/site-packages/django/utils/encoding.py", line 88, in force_text
    raise DjangoUnicodeDecodeError(s, *e.args)
DjangoUnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128). You passed in <Address: [Bad Unicode data]> (<class 'ankets.models.Address'>)
```

My resolve: in file nullablecharfield/forms/fields.py
I chage line 19 from

```
        return smart_str(value)
```

to

```
        return value
```

**Comment by alepane21** [comment]
Hi there,
about this error ... are you sure that the data in the DB are clean?
What version of Django and Python are you using?

Let me know!
Thanks!

Il 16/12/2015 19:01, RockBomber ha scritto:

**Comment by RockBomber** [comment]
Versions indicated in title: Python 2.7, Django 1.9

My model definition:

``` python
from django.db import models
from nullablecharfield.db.models.fields import CharNullField

class Address(models.Model):
    address = CharNullField(blank=True, null=True, max_length=1000)
    country = CharNullField(blank=True, null=True, max_length=255)
    region = CharNullField(blank=True, null=True, max_length=255)
    province = CharNullField(blank=True, null=True, max_length=255)
    street = CharNullField(blank=True, null=True, max_length=255)
    locality = CharNullField(blank=True, null=True, max_length=255)
    house = CharNullField(blank=True, null=True, max_length=255)
    housing = CharNullField(blank=True, null=True, max_length=255)
    building = CharNullField(blank=True, null=True, max_length=255)
    flat = CharNullField(blank=True, null=True, max_length=255)
    phone = CharNullField(blank=True, null=True, max_length=255)
    postIndex = CharNullField(blank=True, null=True, max_length=255)
    town = CharNullField(blank=True, null=True, max_length=255)

    def __unicode__(self):
        return u'{}'.format(self.address)
```

**Comment by alepane21** [comment]
Sorry, I meant the version with patch number, like python 2.7.8. Django 1.9 doesn't have a patch version still, so that's my fault!

## Thanks again for your time.

Alessandro Pagnin

Il 17 Dicembre 2015 09:21:03 CET, RockBomber notifications@github.com ha scritto:

**Comment by RockBomber** [comment]
I have Python 2.7.8

**Comment by Skorpyon** [comment]
@RockBomber I hope Django will remove support Python2 and everybody move to Py3. This stupid cross-python support problems is ugly
